spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

logging:
  level:
    root: warn
    com.hubeao: info
  file: log/blog-pro.log
server:
  port: 8081